---

- name: symlink ~/.bash_dotfiles
  file:
    src: "{{ role_path }}/files/bash_dotfiles"
    dest: ~/.bash_dotfiles
    state: link
    force: yes

- blockinfile:
    name: ~/.bashrc
    block: |
      if [[ -f ~/.bash_dotfiles ]]; then
        . ~/.bash_dotfiles
      fi
    marker: '# {mark} ANSIBLE MANAGED BLOCK [dotfiles]'
