---

- name: symlink ~/.bash_dotfiles
  ansible.builtin.file:
    src: "{{ role_path }}/files/bash_dotfiles"
    dest: ~/.bash_dotfiles
    state: link
    force: yes

- name: append to ~/.bashrc
  ansible.builtin.blockinfile:
    path: ~/.bashrc
    block: |
      [[ -f ~/.bash_dotfiles ]] && source ~/.bash_dotfiles
    marker: '# {mark} ANSIBLE MANAGED BLOCK [dotfiles]'
