---

- file:
    src: "{{ role_path }}/files/bashrc"
    dest: ~/.bash_dotfiles
    state: link

- blockinfile:
    path: ~/.bashrc
    block: |
      if [[ -f ~/.bash_dotfiles ]]; then
        . ~/.bash_dotfiles
      fi
    marker: '# {mark} ANSIBLE MANAGED BLOCK [dotfiles]'

