---

- name: include vars
  include_vars: "{{ ansible_os_family }}.yml"

- name: install packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ python_build_tools_packages }}"
  become: yes
