---

- hosts: localhost
  connection: local
  any_errors_fatal: yes
  vars:
    os_short_name: "{{ ansible_os_family | regex_replace('([a-zA-Z0-9]+).*', '\\1') | lower }}"
  roles:
    - role: mintty
    - role: bash
    - role: git
    - role: tmux
    - role: fd
    - role: fzf
    - role: vim
    - role: pstree
      when: os_short_name == 'mingw64'
