---

aliases:
  - { name: 'ls', value: 'ls -p --color=auto --group-directories-first' }
  - { name: 'la', value: 'ls -pA --color=auto --group-directories-first' }
  - { name: 'll', value: 'ls -plh --color=auto --group-directories-first --time-style=long-iso' }
  - { name: 'lla', value: 'ls -plhA --color=auto --group-directories-first --time-style=long-iso' }
  - { name: 'grep', value: 'grep --color=auto' }
  - { name: 'egrep', value: 'egrep --color=auto' }
  - { name: 'fgrep', value: 'fgrep --color=auto' }
  - { name: 'rgrep', value: 'rgrep --color=auto' }
  - { name: 'vi', value: 'vi --noplugin' }

local_vars:
  - { name: 'C_DEFAULT', value: '\[\033[m\]' }
  - { name: 'C_BLACK', value: '\[\033[30m\]' }
  - { name: 'C_RED', value: '\[\033[31m\]' }
  - { name: 'C_GREEN', value: '\[\033[32m\]' }
  - { name: 'C_YELLOW', value: '\[\033[33m\]' }
  - { name: 'C_BLUE', value: '\[\033[34m\]' }
  - { name: 'C_MAGENTA', value: '\[\033[35m\]' }
  - { name: 'C_CYAN', value: '\[\033[36m\]' }
  - { name: 'C_WHITE', value: '\[\033[37m\]' }
  - { name: 'C_BRBLACK', value: '\[\033[1;30m\]' }
  - { name: 'C_BRRED', value: '\[\033[1;31m\]' }
  - { name: 'C_BRGREEN', value: '\[\033[1;32m\]' }
  - { name: 'C_BRYELLOW', value: '\[\033[1;33m\]' }
  - { name: 'C_BRBLUE', value: '\[\033[1;34m\]' }
  - { name: 'C_BRMAGENTA', value: '\[\033[1;35m\]' }
  - { name: 'C_BRCYAN', value: '\[\033[1;36m\]' }
  - { name: 'C_BRWHITE', value: '\[\033[1;37m\]' }
  - { name: 'C_BG_BLACK', value: '\[\033[40m\]' }
  - { name: 'C_BG_RED', value: '\[\033[41m\]' }
  - { name: 'C_BG_GREEN', value: '\[\033[42m\]' }
  - { name: 'C_BG_YELLOW', value: '\[\033[43m\]' }
  - { name: 'C_BG_BLUE', value: '\[\033[44m\]' }
  - { name: 'C_BG_MAGENTA', value: '\[\033[45m\]' }
  - { name: 'C_BG_CYAN', value: '\[\033[46m\]' }
  - { name: 'C_BG_WHITE', value: '\[\033[47m\]' }

env_vars:
  - { name: 'TZ', value: 'JST-9' }
  - name: 'PS1'
    value: |-
      ${C_YELLOW}>[ES=\$?, \$(date +'%F %T %Z')]${C_DEFAULT}
      ${C_GREEN}[\u@\h \W]${C_DEFAULT}\$ 

