---

rg_version: >-
  {{ lookup('url', 'https://api.github.com/repos/BurntSushi/ripgrep/releases')
     |from_json|map(attribute='tag_name')
     |select('match', '^[0-9\.]+$')|first }}

rg_deb_base_url: "https://github.com/BurntSushi/ripgrep/releases/download"
rg_deb_file: "ripgrep_{{ rg_version }}_amd64.deb"
rg_deb_url: "{{ rg_deb_base_url }}/{{ rg_version }}/{{ rg_deb_file }}"

rg_repo_base_url: "https://copr.fedorainfracloud.org/coprs/carlwgeorge/ripgrep/repo/epel-7"
rg_repo_file: "carlwgeorge-ripgrep-epel-7.repo"
rg_repo_url: "{{ rg_repo_base_url }}/{{ rg_repo_file }}"

