---

- package:
    name: "{{ item }}"
    state: present
  with_items:
    - autoconf
    - automake
  become: yes

- package:
    name: "{{ item }}"
    state: present
  with_items:
    - pkg-config
  become: yes
  when: ansible_os_family == 'Debian'

