---

- git:
    repo: "https://github.com/universal-ctags/ctags.git"
    dest: "~/.ctags"

- name: "pwd"
  command: "pwd"
  args:
    chdir: "~/.ctags"
  register: ctags_pwd
  changed_when: False

- name: "./autogen.sh && ./configure"
  shell: |
    ./autogen.sh && ./configure
  args:
    chdir: "{{ ctags_pwd.stdout }}"

- make:
    chdir: "{{ ctags_pwd.stdout }}"

- make:
    chdir: "{{ ctags_pwd.stdout }}"
    target: install
  become: yes

