---

- name: git clone
  git:
    repo: "https://github.com/universal-ctags/ctags.git"
    dest: "{{ ctags_build_dir }}"

- name: get expanded path
  command: pwd
  args:
    chdir: "{{ ctags_build_dir }}"
  register: _pwd
  changed_when: False

- block:
    - name: sh autogen.sh
      command: sh autogen.sh
      args:
        chdir: "{{ _build_dir }}"
    - name: ./configure
      command: ./configure
      args:
        chdir: "{{ _build_dir }}"
    - name: make
      make:
        chdir: "{{ _build_dir }}"
    - name: make install
      make:
        chdir: "{{ _build_dir }}"
        target: install
      become: yes
  vars:
    _build_dir: "{{ _pwd.stdout }}"
