---

- name: download binary
  get_url:
    url: "{{ rg_deb_url }}"
    dest: /tmp/ripgrep.deb

- name: install package
  apt:
    deb: /tmp/ripgrep.deb
  environment:
    - http_proxy: "{{ lookup('env', 'http_proxy') | default(omit) }}"
    - https_proxy: "{{ lookup('env', 'https_proxy') | default(omit) }}"
    - no_proxy: "{{ lookup('env', 'no_proxy') | default(omit) }}"
  become: yes
