---

- yum:
    name: yum-utils
    state: present
  become: yes

- name: add repository
  command: "yum-config-manager --add-repo {{ rg_repo_url }}"
  args:
    chdir: "/etc/yum.repos.d"
    creates: "{{ rg_repo_file }}"
  become: yes

- yum:
    name: ripgrep
    state: present
  become: yes
