---

- name: install package
  ansible.builtin.package:
    name: tmux
    state: present

- name: install plugins
  ansible.builtin.git:
    repo: "https://github.com/{{ item.owner }}/{{ item.name }}"
    dest: "~/.tmux/plugins/{{ item.name }}"
    version: "{{ item.version | default(omit) }}"
  with_items: "{{ tmux_plugins }}"

- name: symlink ~/.tmux.conf
  ansible.builtin.file:
    src: "{{ role_path }}/files/tmux.conf"
    dest: ~/.tmux.conf
    state: link
    force: yes

# - name: tic
#   ansible.builtin.command:
#     cmd: tic -x {{ role_path }}/files/{{ item }}
#   with_items:
#     - xterm.terminfo
#     - tmux.terminfo
#   become: yes
