---

- name: git clone
  git:
    repo: "https://github.com/pyenv/pyenv.git"
    dest: "~/.pyenv"

- name: install plugins
  git:
    repo: "https://github.com/pyenv/{{ item }}.git"
    dest: "~/.pyenv/plugins/{{ item }}"
  with_items: "{{ pyenv_plugins }}"

