---

- name: install package
  package:
    name: vim
    state: present
  become: yes

- name: symlink ~/.vimrc
  file:
    src: "{{ role_path }}/files/vimrc"
    dest: ~/.vimrc
    state: link
    force: yes
