---

- name: install package
  ansible.builtin.package:
    name: vim
    state: present

- name: symlink ~/.vimrc
  ansible.builtin.file:
    src: "{{ role_path }}/files/vimrc"
    dest: ~/.vimrc
    state: link
    force: yes

- name: install plugins
  ansible.builtin.shell:
    cmd: vim +'PlugInstall --sync' +qall &>/dev/null </dev/tty
