#!/usr/bin/env bash
# -*- coding: utf-8 -*-
set -eo pipefail

fzf_org="${MINGW_PREFIX}"/bin/fzf
[[ -e ~/.fzf/bin/fzf ]] && fzf_org=~/.fzf/bin/fzf

if [[ $(tty) =~ ^/dev/cons ]]; then
  exec "${fzf_org}" "$@"
  exit
fi

prefix="$(basename "${BASH_SOURCE:-$0}")-${UID:-$(id -u)}"
tmpdir="$(mktemp -dp "${TMPDIR:-/tmp}" "${prefix}.XXXXX")"
trap "rm -rf -- '${tmpdir}'" EXIT

args=
[[ $# -ge 1 ]] && args=$(printf ' %q' "$@")

if [[ -t 0 ]]; then
  winpty </dev/tty >/dev/tty -- bash -c \
    "printf ' '; '${fzf_org}'${args} >'${tmpdir}'/output"
  cat "${tmpdir}"/output
else
  cat - >"${tmpdir}"/input
  winpty </dev/tty >/dev/tty -- bash -c \
    "printf ' '; '${fzf_org}'${args} <'${tmpdir}'/input >'${tmpdir}'/output"
  cat "${tmpdir}"/output
fi
